import type { LevelConfig } from '@/types/circuit';

export const CAMPAIGN_LEVELS: LevelConfig[] = [
  // ==========================================
  // TIER 1: FOUNDATIONS (LV 01 ~ LV 04)
  // ==========================================
  {
    levelId: 'lvl-01',
    title: 'The First Spring',
    chapter: 'Chapter 1: The Water Valves',
    tier: 1,
    description: 'Welcome, young Hydro-Engineer! Turn the rotary water valve to open the aqueduct and irrigate the sunflower farmland.',
    hint: 'Click on the Rotary Valve (Source A) to open water flow.',
    pedagogicalGoal: 'Learn that an Input Valve switches between 0 (Dry / Off) and 1 (Flowing / On).',
    parSteps: 1,
    gridSize: { cols: 5, rows: 3 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: false,
        label: 'Valve A',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 4, y: 1 },
        targetState: true,
        label: 'Sunflower Field',
        targetType: 'SUNFLOWER',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'tgt-1', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-02',
    title: 'Twin Currents',
    chapter: 'Chapter 1: The Water Valves',
    tier: 1,
    description: 'The AND Gate (Dual-Impeller Lock) requires pressure on BOTH inputs to spin both turbines and lift the heavy iron gate.',
    hint: 'Both Valve A and Valve B must be turned ON for the AND gate to open.',
    pedagogicalGoal: 'Master the AND Circuit Gate: Output is 1 only when BOTH inputs are 1 (1 AND 1 = 1).',
    parSteps: 2,
    gridSize: { cols: 6, rows: 4 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: false,
        label: 'Valve A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3 },
        state: false,
        label: 'Valve B',
      },
      {
        id: 'gate-and',
        type: 'AND',
        position: { x: 3, y: 2 },
        label: 'AND Gate',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 5, y: 2 },
        targetState: true,
        label: 'Carrot Patch',
        targetType: 'CARROT',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-and', inputSlot: 0 },
      { id: 'p2', from: 'src-b', to: 'gate-and', inputSlot: 1 },
      { id: 'p3', from: 'gate-and', to: 'tgt-1', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-03',
    title: 'River Confluence',
    chapter: 'Chapter 1: The Water Valves',
    tier: 1,
    description: 'The OR Gate (Curved Funnel) allows water to flow down to the farmland if EITHER upstream valve is open.',
    hint: 'Turn on Valve A OR Valve B (or both) to supply water to the reservoir tank.',
    pedagogicalGoal: 'Master the OR Circuit Gate: Output is 1 if AT LEAST ONE input is 1 (1 OR 0 = 1).',
    parSteps: 1,
    gridSize: { cols: 6, rows: 4 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: false,
        label: 'Valve A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3 },
        state: false,
        label: 'Valve B',
      },
      {
        id: 'gate-or',
        type: 'OR',
        position: { x: 3, y: 2 },
        label: 'OR Gate',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 5, y: 2 },
        targetState: true,
        label: 'Hydration Tank',
        targetType: 'TANK',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-or', inputSlot: 0 },
      { id: 'p2', from: 'src-b', to: 'gate-or', inputSlot: 1 },
      { id: 'p3', from: 'gate-or', to: 'tgt-1', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-04',
    title: 'The Inverted Siphon',
    chapter: 'Chapter 1: The Water Valves',
    tier: 1,
    description: 'The NOT Gate (Triangle Inverter) inverts the signal: when input is 0 (dry), the output is 1 (flowing); when input is 1 (water), buoy floats and output becomes 0 (stopped).',
    hint: 'The sunflower farmland wants water! Keep the input valve OFF so the NOT gate outputs water.',
    pedagogicalGoal: 'Master the NOT Inverter Gate: Inverts the signal (NOT 0 = 1, NOT 1 = 0).',
    parSteps: 0,
    gridSize: { cols: 5, rows: 3 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: true,
        label: 'Valve A',
      },
      {
        id: 'gate-not',
        type: 'NOT',
        position: { x: 3, y: 1 },
        label: 'NOT Inverter',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 5, y: 1 },
        targetState: true,
        label: 'Sunflower Field',
        targetType: 'SUNFLOWER',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-not', inputSlot: 0 },
      { id: 'p2', from: 'gate-not', to: 'tgt-1', inputSlot: 0 },
    ],
  },

  // ==========================================
  // TIER 2: INTERMEDIATE COMPOUND LOGIC (LV 05 ~ LV 07)
  // ==========================================
  {
    levelId: 'lvl-05',
    title: 'Meadow Irrigation',
    chapter: 'Chapter 2: Compound Fluid Networks',
    tier: 2,
    description: 'Water must pass through Main Valve A, AND through an OR gate fed by Stream B or C: Valve A AND (Valve B OR Valve C).',
    hint: 'Make sure Valve A is ON, plus at least one of the secondary valves (B or C).',
    pedagogicalGoal: 'Understand multi-stage compound logic circuits combining AND gates with OR gates.',
    parSteps: 2,
    gridSize: { cols: 7, rows: 5 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: false,
        label: 'Canal A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3 },
        state: false,
        label: 'Stream B',
      },
      {
        id: 'src-c',
        type: 'SOURCE',
        position: { x: 1, y: 4.5 },
        state: false,
        label: 'Stream C',
      },
      {
        id: 'gate-or',
        type: 'OR',
        position: { x: 3.5, y: 3.5 },
        label: 'OR Gate (B or C)',
      },
      {
        id: 'gate-and',
        type: 'AND',
        position: { x: 5, y: 2 },
        label: 'AND Gate',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 7, y: 2 },
        targetState: true,
        label: 'Sunflower Meadow',
        targetType: 'SUNFLOWER',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-b', to: 'gate-or', inputSlot: 0 },
      { id: 'p2', from: 'src-c', to: 'gate-or', inputSlot: 1 },
      { id: 'p3', from: 'src-a', to: 'gate-and', inputSlot: 0 },
      { id: 'p4', from: 'gate-or', to: 'gate-and', inputSlot: 1 },
      { id: 'p5', from: 'gate-and', to: 'tgt-1', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-06',
    title: 'Cactus & Carrot Sanctuary',
    chapter: 'Chapter 2: Compound Fluid Networks',
    tier: 2,
    description: 'A dual-target challenge! The Desert Cactus must stay DRY (0), while the Carrot Patch must be WET (1). Route the circuit correctly!',
    hint: 'The Cactus connects through a NOT Inverter; the Carrot connects through an AND gate.',
    pedagogicalGoal: 'Master multi-target circuit routing where different endpoints demand different logic states.',
    parSteps: 2,
    gridSize: { cols: 7, rows: 5 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 2 },
        state: false,
        label: 'Supply A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 4 },
        state: false,
        label: 'Valve B',
      },
      {
        id: 'gate-not',
        type: 'NOT',
        position: { x: 3, y: 1 },
        label: 'NOT Gate',
      },
      {
        id: 'gate-and',
        type: 'AND',
        position: { x: 4, y: 3 },
        label: 'AND Gate',
      },
      {
        id: 'tgt-cactus',
        type: 'TARGET',
        position: { x: 6.5, y: 1 },
        targetState: false, // Wants DRY (0)
        label: 'Cactus Bed (Dry)',
        targetType: 'TANK',
      },
      {
        id: 'tgt-carrot',
        type: 'TARGET',
        position: { x: 6.5, y: 3 },
        targetState: true, // Wants WET (1)
        label: 'Carrot Farmland (Wet)',
        targetType: 'CARROT',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-not', inputSlot: 0 },
      { id: 'p2', from: 'gate-not', to: 'tgt-cactus', inputSlot: 0 },
      { id: 'p3', from: 'src-a', to: 'gate-and', inputSlot: 0 },
      { id: 'p4', from: 'src-b', to: 'gate-and', inputSlot: 1 },
      { id: 'p5', from: 'gate-and', to: 'tgt-carrot', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-07',
    title: 'The Teeter-Totter Aqueduct',
    chapter: 'Chapter 2: Compound Fluid Networks',
    tier: 2,
    description: 'The XOR Gate (Exclusive-OR) outputs 1 only when inputs are DIFFERENT (one valve ON and one valve OFF). When both are ON or both OFF, it outputs 0.',
    hint: 'Set inputs to 1 and 0 (or 0 and 1) to trigger the XOR gate.',
    pedagogicalGoal: 'Master the XOR (Exclusive OR) Circuit Gate: Outputs 1 when inputs differ, 0 when identical.',
    parSteps: 1,
    gridSize: { cols: 6, rows: 4 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: true,
        label: 'Valve A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3 },
        state: true,
        label: 'Valve B',
      },
      {
        id: 'gate-xor',
        type: 'XOR',
        position: { x: 3, y: 2 },
        label: 'XOR Gate',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 5, y: 2 },
        targetState: true,
        label: 'Sunflower Field',
        targetType: 'SUNFLOWER',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-xor', inputSlot: 0 },
      { id: 'p2', from: 'src-b', to: 'gate-xor', inputSlot: 1 },
      { id: 'p3', from: 'gate-xor', to: 'tgt-1', inputSlot: 0 },
    ],
  },

  // ==========================================
  // TIER 3: APPLIED REAL-WORLD LOGIC (LV 08 ~ LV 10)
  // ==========================================
  {
    levelId: 'lvl-08',
    title: 'Automated Greenhouse Alert',
    chapter: 'Chapter 3: Real-World Hydro-Computers',
    tier: 3,
    description: 'The Emergency Sprinkler Alarm triggers when Master Power A is ON, AND either the High Temp Sensor B is active OR Rain Sensor C is OFF (via NOT gate).',
    hint: 'Alarm = Power A AND (Sensor B OR NOT Sensor C).',
    pedagogicalGoal: 'Construct real-world industrial emergency alarm circuits with sensor inversion.',
    parSteps: 2,
    gridSize: { cols: 8, rows: 5 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: false,
        label: 'Power A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3 },
        state: false,
        label: 'Temp Sensor B',
      },
      {
        id: 'src-c',
        type: 'SOURCE',
        position: { x: 1, y: 4.5 },
        state: true,
        label: 'Rain Sensor C',
      },
      {
        id: 'gate-not',
        type: 'NOT',
        position: { x: 3, y: 4.5 },
        label: 'NOT Inverter',
      },
      {
        id: 'gate-or',
        type: 'OR',
        position: { x: 4.5, y: 3.5 },
        label: 'OR Gate',
      },
      {
        id: 'gate-and',
        type: 'AND',
        position: { x: 6, y: 2 },
        label: 'AND Gate',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 8, y: 2 },
        targetState: true,
        label: 'Sprinkler Alarm',
        targetType: 'TANK',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-c', to: 'gate-not', inputSlot: 0 },
      { id: 'p2', from: 'src-b', to: 'gate-or', inputSlot: 0 },
      { id: 'p3', from: 'gate-not', to: 'gate-or', inputSlot: 1 },
      { id: 'p4', from: 'src-a', to: 'gate-and', inputSlot: 0 },
      { id: 'p5', from: 'gate-or', to: 'gate-and', inputSlot: 1 },
      { id: 'p6', from: 'gate-and', to: 'tgt-1', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-09',
    title: 'Airlock Decompression Interlock',
    chapter: 'Chapter 3: Real-World Hydro-Computers',
    tier: 3,
    description: 'Submarine Safety System! The Safe Indicator must only light up if NOT both Inner Door Sensor A AND Vent Valve B are active. This is a Universal NAND Gate: NOT (A AND B)!',
    hint: 'Decompression hazard occurs when both A and B are 1. Prevent hazard by setting at least one to 0.',
    pedagogicalGoal: 'Discover the Universal NAND Circuit Gate (AND gate connected into a NOT inverter).',
    parSteps: 1,
    gridSize: { cols: 7, rows: 4 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1 },
        state: true,
        label: 'Inner Door A',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3 },
        state: true,
        label: 'Chamber Vent B',
      },
      {
        id: 'gate-and',
        type: 'AND',
        position: { x: 3, y: 2 },
        label: 'AND Gate',
      },
      {
        id: 'gate-not',
        type: 'NOT',
        position: { x: 5, y: 2 },
        label: 'NOT Inverter',
      },
      {
        id: 'tgt-1',
        type: 'TARGET',
        position: { x: 7, y: 2 },
        targetState: true,
        label: 'Safe Interlock (NAND)',
        targetType: 'TANK',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-and', inputSlot: 0 },
      { id: 'p2', from: 'src-b', to: 'gate-and', inputSlot: 1 },
      { id: 'p3', from: 'gate-and', to: 'gate-not', inputSlot: 0 },
      { id: 'p4', from: 'gate-not', to: 'tgt-1', inputSlot: 0 },
    ],
  },
  {
    levelId: 'lvl-10',
    title: 'The Hydraulic Half-Adder',
    chapter: 'Chapter 3: Real-World Hydro-Computers',
    tier: 3,
    description: 'How modern CPUs do arithmetic with 1s and 0s! A Binary Half-Adder uses an XOR gate to compute the Sum bit (A XOR B) and an AND gate to compute the Carry bit (A AND B). Calculate 1 + 1 = 10 in binary (Sum=0, Carry=1)!',
    hint: 'Turn ON both Input Bit A and Input Bit B to calculate 1 + 1: Sum Bit becomes 0 (dry) and Carry Bit becomes 1 (watered)!',
    pedagogicalGoal: 'Witness how logic gates combine into the fundamental arithmetic adder building block of modern CPUs.',
    parSteps: 2,
    gridSize: { cols: 8, rows: 5 },
    nodes: [
      {
        id: 'src-a',
        type: 'SOURCE',
        position: { x: 1, y: 1.5 },
        state: false,
        label: 'Bit A (Value: 1)',
      },
      {
        id: 'src-b',
        type: 'SOURCE',
        position: { x: 1, y: 3.5 },
        state: false,
        label: 'Bit B (Value: 1)',
      },
      {
        id: 'gate-xor',
        type: 'XOR',
        position: { x: 4, y: 1.5 },
        label: 'Sum Gate (XOR)',
      },
      {
        id: 'gate-and',
        type: 'AND',
        position: { x: 4, y: 3.5 },
        label: 'Carry Gate (AND)',
      },
      {
        id: 'tgt-sum',
        type: 'TARGET',
        position: { x: 7, y: 1.5 },
        targetState: false, // Wants Sum = 0 when 1+1
        label: 'Sum Bit (2⁰ = 0)',
        targetType: 'CARROT',
      },
      {
        id: 'tgt-carry',
        type: 'TARGET',
        position: { x: 7, y: 3.5 },
        targetState: true, // Wants Carry = 1 when 1+1
        label: 'Carry Farmland (2¹ = 1)',
        targetType: 'SUNFLOWER',
      },
    ],
    pipes: [
      { id: 'p1', from: 'src-a', to: 'gate-xor', inputSlot: 0 },
      { id: 'p2', from: 'src-b', to: 'gate-xor', inputSlot: 1 },
      { id: 'p3', from: 'src-a', to: 'gate-and', inputSlot: 0 },
      { id: 'p4', from: 'src-b', to: 'gate-and', inputSlot: 1 },
      { id: 'p5', from: 'gate-xor', to: 'tgt-sum', inputSlot: 0 },
      { id: 'p6', from: 'gate-and', to: 'tgt-carry', inputSlot: 0 },
    ],
  },
];
